apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dispatcharr
  name: dispatcharr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcharr
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      securityContext:
        fsGroup: 1000
        supplementalGroups: [3100]
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            [
              "sh",
              "-c",
              "mkdir -p /data/db && chown -R 1000:1000 /data/db && chmod 700 /data/db",
            ]
          volumeMounts:
            - mountPath: /data
              name: dispatcharr-data
      containers:
        - image: ghcr.io/dispatcharr/dispatcharr:0.26.0
          name: dispatcharr
          ports:
            - containerPort: 9191
          securityContext:
            privileged: true
          env:
            - name: DISPATCHARR_ENV
              value: aio
            - name: REDIS_HOST
              value: localhost
            - name: CELERY_BROKER_URL
              value: redis://localhost:6379/0
            - name: DISPATCHARR_LOG_LEVEL
              value: info
          volumeMounts:
            - mountPath: /data
              name: dispatcharr-data
      volumes:
        - name: dispatcharr-data
          persistentVolumeClaim:
            claimName: dispatcharr-data-pvc
