apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dispatcharr
  name: dispatcharr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcharr
  template:
    metadata:
      labels:
        app: dispatcharr
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          securityContext:
            runAsUser: 0
          command:
            [
              "sh",
              "-c",
              "mkdir -p /data/db && chown -R 1000:1000 /data/db && chmod 700 /data/db",
            ]
          volumeMounts:
            - mountPath: /data
              name: dispatcharr-data
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.41.1
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: VPN_TYPE
              value: "wireguard"
            - name: TZ
              value: "Europe/Stockholm"
            - name: DOT
              value: "off"
            - name: DNS_UPSTREAM
              value: "1.1.1.1,8.8.8.8"
          envFrom:
            - secretRef:
                name: openvpn-secrets

        - image: ghcr.io/dispatcharr/dispatcharr:0.26.0
          name: dispatcharr
          ports:
            - containerPort: 9191
          env:
            - name: DISPATCHARR_ENV
              value: aio
            - name: REDIS_HOST
              value: localhost
            - name: CELERY_BROKER_URL
              value: redis://localhost:6379/0
            - name: DISPATCHARR_LOG_LEVEL
              value: info
          volumeMounts:
            - mountPath: /data
              name: dispatcharr-data
      volumes:
        - name: dispatcharr-data
          persistentVolumeClaim:
            claimName: dispatcharr-data-pvc
