apiVersion: v1
kind: Service
metadata:
  labels:
    app: dispatcharr
  name: dispatcharr
spec:
  ports:
    - port: 9191
      protocol: TCP
      targetPort: 9191
  selector:
    app: dispatcharr
  type: ClusterIP
