apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcharr-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-pvc-nfs
  resources:
    requests:
      storage: 2Gi
