apiVersion: v1
kind: Service
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: webui
      protocol: TCP

    - name: quiui
      port: 7476
      targetPort: quiui
      protocol: TCP

    - name: metrics
      port: 9074
      targetPort: metrics

    - name: torrent-tcp
      port: 6881
      targetPort: 6881
      protocol: TCP

    - name: torrent-udp
      port: 6881
      targetPort: 6881
      protocol: UDP
