apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: https://k8s-homelab-prod.vault.azure.net
      tenantId: 902e9270-c7d1-4e19-abd7-cac829333336
      authSecret:
        clientId:
          name: azure-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: clientSecret
          namespace: external-secrets
