apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: z2m-data-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nvme-nfs
  resources:
    requests:
      storage: 1Gi
