apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  releaseName: garage
  targetNamespace: garage
  interval: 10m

  chart:
    spec: 
      chart: script/helm/garage
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
        
  values:
    garage:
      s3:
        api:
          region: "garage"
          rootDomain: ""
        web:
          rootDomain: ""
          index: "index.html"
    
    deployment:
      replicaCount: 3

    persistence:
      meta:
        storageClass: truenas-pvc-nfs
        size: 10Gi
      data:
        storageClass: truenas-pvc-nfs
        size: 10Gi
    
    service:
      type: ClusterIP

    ingress:
      s3:
        api:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: s3.christophervestman.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: garage-s3-tls
              hosts:
                - s3.christophervestman.com

        web:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: garage.christophervestman.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: garage-web-tls
              hosts:
                - garage.christophervestman.com
