apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/deuxfleurs-org/garage
  ref:
    branch: main
