apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-config-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nvme-nfs
  resources:
    requests:
      storage: 5Gi
