apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-config-pvc-v2
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
