apiVersion: v1
kind: Service
metadata:
  labels:
    app: transmute
  name: transmute
spec:
  ports:
    - port: 3313
      protocol: TCP
      targetPort: 3313
  selector:
    app: transmute
  type: ClusterIP
