apiVersion: v1
data:
  DISCORD_APP_ID: ENC[AES256_GCM,data:kGwsRzDRPxM8kBrFu/lxELM2261BWAXetXWgyw==,iv:m3cI4MBxiB5ufl7hHgA0RMBaIywI3EXnlrYPE3FLKQg=,tag:2dftYdyA9Ob6Fmvn1fXuRw==,type:str]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:nJejGU7BcG9fiGYfrlV68klhBXFFJJvRzxN/pKP7q3XzcDpUy396R9r4IqOGQ36NniqG6ncZUSfFUECGORYIWLoERkQ+KHy3VVQLTBawpFs22+28Yei4pQkN7ITKJZ64Zkt/jQ==,iv:V5dzyfle3fQkjdGgMpuwiXaBT5pGuAtvKgjoo4qQVgY=,tag:KTmNMXItVoW76td4ERD6Xg==,type:str]
  DISCORD_SERVER_ID: ENC[AES256_GCM,data:qRc6O5Lb+PWMpppdUiaAY5X4L5dxjrNh2lhHZg==,iv:FCBVWIaw0Blp3KAMXa8Ai3niT8v3ZzISVqXybgA2VVs=,tag:qQuRwbF6FkDhqSod/3t5EQ==,type:str]
  OAUTH_CLIENT_ID: ENC[AES256_GCM,data:YBe+blXSuDNJtN/m+LYl3j1FfxE2L5j3,iv:b/Nq/JRsHeM9FZCv9HOkQH6lJwKQdCkP+bVGIXi7tzU=,tag:b3WNv9f5Kd5IgA46VN5EKQ==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cTxKtL0gI37Q2KfMhmM9peEze1USbljAk8OG7x6hAeCuueoVzQgDulCvdDg=,iv:wodhej+HvbE/QJ+x1JekNsbkfrAF6pGh9LmSu4b6h2M=,tag:sxz7u8daOQS6pyHOBS8E4Q==,type:str]
  REDDIT_ACCESS_URL: ENC[AES256_GCM,data:EaKMFSzmfncutVqm34o7EMogi+F0cTlRWCqrQGm0s7bkUXImyQjqs4QUa6hizmdQIYWXix0zCp1nP5EB,iv:Boolh0UfzDutJs/mEGU8t0ip6SFlRsRcQcsU4Pn6UDk=,tag:LWD3La9CtivPksiaVqHWSg==,type:str]
  REDDIT_PASSWORD: ENC[AES256_GCM,data:OAn5lVxeNQo98sJT381LXQ==,iv:RZm/sCPTiP5yOGgnx1LZfvn7vkD08QFj5iKTpC/Nd38=,tag:KUesHY7QL2A31HMuSavMqA==,type:str]
  REDDIT_USERNAME: ENC[AES256_GCM,data:zWHQz4NYEJrH86hDIEp83XVP2hA=,iv:Opx8ckNTxjSOSMgnattVsMzTWopIm2TN6Ap0oQ2D3/k=,tag:AU4KvnX9NqGExUJjMIcbyQ==,type:str]
  WALLHAVEN_API_KEY: ENC[AES256_GCM,data:taOdvQsWLSez4Leaq/85imAo+J+Q4rzxGVsmW25gmCTVDvqtw364fV+CGhXsaN8c,iv:5/skvZ19YvqxUvLN4v3g09xjM1aptB7DXaPaLfQN6h8=,tag:Zek/JkbHPDTw72QRDvI3Zg==,type:str]
  WALLHAVEN_BASE_URL: ENC[AES256_GCM,data:iLsB6sLfHmSMHjBKfHTg363S8yR6ZkpuOwMqLUdojKtm2omgScI/EA==,iv:7TnIadeKuXxjR25ICPuKl7jPmD75obbxOGLstUYXlOM=,tag:0k5aihNFsHywYMGfmVAvlg==,type:str]
  WALLHAVEN_COLLECTION_ID: ENC[AES256_GCM,data:nQqrsdIAqPpOU9AK,iv:Be5Ugvgvvnl1Dpr7ppqAsZk+tJC0GOHrrByOCUJTYs4=,tag:gdfnmqErhDGZXLsZAgKEkw==,type:str]
  WALLHAVEN_LATEST_URL: ENC[AES256_GCM,data:qBFRxa6AbFvEcj3SQyUlPkg3bXPEOxp/KJsgW/vNkTXO4uxM6lUp0x5iNOY2mks8s6EuBj83lGRMK93mb4xxY0sXzaL7IUB4kGLlIC6PNfnNcByyLMENsDgZ3RKebJn7vK/Q60CmWio46aebrR7w7obOqfTHmHhbfPoKQQ==,iv:o+HQWMqNnEIHK3OxafKBIdmOSKpc4cyfBWvN1ff27L8=,tag:Qs6J3TQuKN6QunFer3DRFw==,type:str]
  WALLHAVEN_USERNAME: ENC[AES256_GCM,data:EbxPkKv6vVtPx2ob,iv:8qlrGoWjMCLNU5Je/r6W3s7lxVFm8EiIx8kzSe6bv+o=,tag:w+1HsC6GmddpbrZrMCrF/A==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: discord-bot-env
sops:
  age:
    - recipient: age14l4x2993zh3lavuyc75d669889zqjzap384um9ngv08eeh9w35nqnw3jd8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZGE0VDVZSHJnS2lmbm0v
        bU4wUlo3VXp1d0k4Zk9QT3ZFMk9TV0JTdVNBCjdMTWZHM2ZGS1phRFlYZEZ1Ni90
        TDI5eFY5UkJqamYrK2NOaUVqOTQ2OGMKLS0tIHVGdWZ3dWNkWWpSNGhYamZlYjFL
        cVZkRHcvMUF2VThiYlRsWkd4NklSRFUK3KdM04RHmKfPIhMakupneMurnEkKV1yE
        fJL6yf0TqlgFb0Bzhyjo/FxTwucFRgcOcFdLUPMeTcFYZ/QXXkOdJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-07T21:43:34Z"
  mac: ENC[AES256_GCM,data:y3qS7CUZc4qlWCigBMCuW2SPYdIspEFLg/KYZ9Yb1layP81x0f9JLt9l1JRGZfwIZBTEGHQ7OPr7JgAK5K9djIKrFqU7KT4BNm7dGhgl2D8rEhe05IpvPzFOF5FYs2HotzRsZIZHJGANkLiSPzx+JBbiJgKIzp+0Lo6UZtTt/yM=,iv:/xs9/M/f/FDthUogNwzM6OkJ97ojjEmsZ2rBMGJ5xAI=,tag:75P65A/Kdtz7pD28FYAdKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
