apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-bot-creds
  namespace: discord-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: discord-bot-creds
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_APP_ID
      remoteRef:
        key: discord-app-id
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: discord-bot-token
    - secretKey: DISCORD_SERVER_ID
      remoteRef:
        key: discord-server-id
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: discord-oauth-client-id
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: discord-oauth-client-secret
    - secretKey: REDDIT_PASSWORD
      remoteRef:
        key: reddit-password
    - secretKey: REDDIT_USERNAME
      remoteRef:
        key: reddit-username
    - secretKey: WALLHAVEN_API_KEY
      remoteRef:
        key: wallhaven-api-key
    - secretKey: WALLHAVEN_COLLECTION_ID
      remoteRef:
        key: wallhaven-collection-id
    - secretKey: WALLHAVEN_LATEST_URL
      remoteRef:
        key: wallhaven-latest-url
    - secretKey: WALLHAVEN_USERNAME
      remoteRef:
        key: wallhaven-username

