apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bazarr
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      securityContext:
        fsGroup: 3100
        supplementalGroups: [3100]
      containers:
        - name: bazarr
          image: ghcr.io/linuxserver/bazarr:v1.6.1-ls365@sha256:762f802274598da27255b2e5778f262b2b71b355a23e3812d9ee1520f8dbe37c
          ports:
            - containerPort: 6767
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "3100"
            - name: TZ
              value: Europe/Stockholm
          resources:
            requests:
              memory: 192Mi
            limits:
              memory: 384Mi
          volumeMounts:
            - mountPath: /config
              name: bazarr-config
            - mountPath: /media
              name: media
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc-v2
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
