apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lifedata-db-v1
  namespace: life
spec:
  description: "Postgres cluster for life namespace"
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
  imagePullPolicy: Always
  inheritedMetadata:
    labels:
      app: lifedata-db
      policy-type: database
  instances: 1

  # postgresql:
  #   extensions:
  #     - name: postgis
  #       image:
  #         reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.3-18-trixie
  #       ld_library_path:
  #         - system
  #       env:
  #         - name: GDAL_DATA
  #           value: ${image_root}/share/gdal
  #         - name: PROJ_DATA
  #           value: ${image_root}/share/proj

  storage:
    size: 2Gi
    storageClass: longhorn
    resizeInUseVolumes: true

  walStorage:
    size: 2Gi
    storageClass: longhorn

  superuserSecret:
    name: lifedata-db-superuser

  # # FRESH INSTALL: contains no backup. Have to use initdb
  # bootstrap:
  #   initdb:
  #     database: lifedata
  #     owner: lifedata
  #     secret:
  #       name: lifedata-db-credentials

  bootstrap:
    pg_basebackup:
      source: lifedata-db-v0

  externalClusters:
    - name: lifedata-db-v0
      connectionParameters:
        host: lifedata-db-v0-rw.life.svc.cluster.local
        user: streaming_replica
        dbname: lifedata
        sslmode: verify-ca
      sslKey:
        name: lifedata-db-v0-replication
        key: tls.key
      sslCert:
        name: lifedata-db-v0-replication
        key: tls.crt
      sslRootCert:
        name: lifedata-db-v0-ca
        key: ca.crt

  # DISASTER RECOVERY: Once a backup exists, replace the initdb with the block below
  # bootstrap:
  #   recovery:
  #     source: lifedata-db-hexabyte
  #     database: lifedata
  #     owner: lifedata
  #     secret:
  #       name: lifedata-db-credentials
  # externalClusters:
  #   - name: lifedata-db-hexabyte
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: lifedata-db-backup-hexabyte
  #         serverName: lifedata-db

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: lifedata-db-backup-hexabyte

  managed:
    services:
      disabledDefaultServices: ["r", "ro"]

    roles:
      - name: lifedata
        ensure: present
        login: true
        createdb: false
        passwordSecret:
          name: lifedata-db-credentials
      - name: wikijs
        ensure: present
        login: true
        createdb: false
        passwordSecret:
          name: wikijs-db-credentials
      - name: outline
        ensure: present
        login: true
        createdb: false
        passwordSecret:
          name: outline-db-credentials
