apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: lifedata-db-daily-hexabyte
  namespace: life
spec:
  immediate: true
  schedule: "0 30 3 * * *"
  cluster:
    name: lifedata-db-v0
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: lifedata-db-backup-hexabyte
  backupOwnerReference: cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: lifedata-db-ondemand
  namespace: life
spec:
  cluster:
    name: lifedata-db-v0
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: lifedata-db-backup-hexabyte
