apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lifedata-db-superuser
  namespace: life
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: lifedata-db-superuser
    creationPolicy: Owner
    template:
      data:
        username: "postgres"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: cnpg-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hexabyte-credentials
  namespace: life
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: hexabyte-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: hexabyte-access-key
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: hexabyte-secret-access-key
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: restic-backup-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lifedata-db-credentials
  namespace: life
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: lifedata-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: "lifedata"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: lifedata-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wikijs-db-credentials
  namespace: life
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: wikijs-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: "wikijs"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: wikijs-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-db-credentials
  namespace: life
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: outline-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: "outline"
        password: "{{ .password }}"
        outline-secret-key: "{{ .secretKey }}"
        outline-utils-secret: "{{ .utilsSecret }}"
        database-uri: "postgresql://outline:{{ .password }}@outline-db-v0-rw.life.svc.cluster.local:5432/outline"

  data:
    - secretKey: password
      remoteRef:
        key: outline-db-password
    - secretKey: secretKey
      remoteRef:
        key: outline-secret-key
    - secretKey: utilsSecret
      remoteRef:
        key: outline-utils-secret
