apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:joGKQFYbFA2y3MEEPXLWkTeEDtzOu4PAqsgkGc3qmh0vi0Sn4Rex2gYJrP/Uem0+q2XLLZziVLCFxkcUPUtvbOXfaaPuTzlGBscnIaWsYctFqVPkcsYCnIC3rcE=,iv:qMNF3pVo+ZbHE9zZOXI5dswPCjzybmJwr5Q6wayhcss=,tag:YdCSxvSgaXMCQJ2qLwL2MA==,type:str]
    secret-key: ENC[AES256_GCM,data:H2T0H6Zush8J6IeoUpm80lJHu0fN+ofTh2IvbZ60bAnxQQhNPEcD/ttgDACaXkgY2wjmGQ18TNeqfpYjY5RpMnTvFOl8LTWHopB0RKoOC185pajemiqVHhR1sb0=,iv:oba4AAqqLso3L5R1VX7kPTLuXvPDfARuqqvbTLdXG9o=,tag:68xwsf4kZxFSyvx9BXpMwQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2025-08-14T09:36:12Z"
    name: porkbun-secret
    namespace: cert-manager
    resourceVersion: "463930"
    uid: 2658405d-4a77-4faa-9b0d-665e412988e0
type: Opaque
sops:
    age:
        - recipient: age14l4x2993zh3lavuyc75d669889zqjzap384um9ngv08eeh9w35nqnw3jd8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSHVmQUMzdExzTkhTaVZX
            WU0xaFJzU0RkS2lxUi93ODAxUFk2dkVDRnc0Clhyd1E3WkwrY0ZPWC9wS3crQVFo
            ay9Wc0ZmaDNkR2JsMEd5OHVFektVaG8KLS0tIElWRWVvRXVyemRYYmE1UjAxeG13
            dWNWaDdQSndOL2hrWTRRbGU5cmMyUUUKXutsCg9GCnAmlYIVT3812wd8ob3vA0S3
            wit8SOuKJzlKNbyooRm9MaKD/155TU0eSu/WcSWg6TauuyrRyWi8MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T09:36:17Z"
    mac: ENC[AES256_GCM,data:vCKG9G3tlmlTrXLEwq7sn14A5XgQEhkMyviCslJaqqxkUc2gSmTLpB2FKTHKdN6tuoUwfoXKtaHNQhaNo3dPWdoXrc4rlok5gf7ZDZnEhXTfPVXkOp09khpuD0hpR26JoSktIXVTuMA39gaNfstjR0H0WcPFI5IVYo57+A3GwQs=,iv:2LT579hTKuFMXag+HoCwl4b7S8aVp8MYb55fAvPjT5g=,tag:MrN4h90gvjnoj75sBiKfNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
