apiVersion: v1
data:
  api-key: ENC[AES256_GCM,data:P0925E2jYzrh9vy9o82Q5BzmZL9MrVO+r0RTZxdyn8BpXenMRwxUfEk3SxRPzMK7xH4CFnjfm1nLO90gyRZ9I0HWuSE6GpQP8r90Htj+PVYFYxO8Aeq/kuflt4Y=,iv:9+/KQK3wKrVQj1wSAIVcUiN+uW5ktjPRM8P6hE9w95Q=,tag:iU7ve4zouK/AVugnLAM0+w==,type:str]
  secret-key: ENC[AES256_GCM,data:TtIoT4WtNURP9D48/XloITVOogyHG3OvTcl7oyZS0PmomU/H74XxqgLrC222B+oLGqVkseZqhl2SF7BFQ8eP4PT5dg7TJELd2e0FrILEarAoZ2B1H79rpY8zeXM=,iv:NsWdDpeEzWRYlR4Vd4Z0ApM1PGhUbYQPhs4YCUyORJI=,tag:pLa6sgBWpPBp0jg/Bhk3yA==,type:str]
kind: Secret
metadata:
  name: porkbun-secret
sops:
  age:
    - recipient: age14l4x2993zh3lavuyc75d669889zqjzap384um9ngv08eeh9w35nqnw3jd8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ3NZWE9JYStCdTdsRko5
        YWFiRXYzK0lhUUJ3aThEM1pRSHlnak54eHpnCk1vMVdSMGZJZDRpZDQ4VE5saWgw
        cW1jODFKTmhHa0VuZnBPV2VYSlhSRUkKLS0tIHB4WE9nVG5DUlpIVkRtdmE2cmVM
        QndrTDFMSU9BWHk2N2tYTDJjVW4wcmsKQGL+pyJ6M/WA39K8IEzr8OooW+XCj9io
        encoVhCalh3w06AfWf8yuXYyYaBnwj0b0v1Qg4rk3Lc8aDvw9BBlkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T20:49:08Z"
  mac: ENC[AES256_GCM,data:13zAu0N710MGShj/tcqW9nchsIKF83XgV8kA1LQRe676RYmGZrx3nPBylYs2qNZwrFehrMhEqDLr2S1KXpBSfId4WaZLi8sQ62I32CGA4T1OF4OaNnNtpu4dHXKdfYv/rsIGzHjWDIBUqVz4Ajua2OFA97sbfg96Idgo51ErgDk=,iv:qlR0nP8o9Z7M384tEX9VOOTqvZbxBrgWCgP0Uw9KvMk=,tag:FKyQItesLrtSCGIbRgJsGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
