apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: paperless
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  namespace: paperless
spec:
  selector:
    app: gotenberg
  ports:
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: paperless
spec:
  selector:
    app: tika
  ports:
    port: 9998
    targetPort: 9998
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: paperless-ngx
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: paperless-ngx
    role: app
  type: ClusterIP
