apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
    role: app
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
        role: app
    spec:
      securityContext:
        fsGroup: 911
        runAsUser: 911
        runAsGroup: 911
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v3.3.1
          name: mealie
          env:
            - name: DB_ENGINE
              value: postgres
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: dbname
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: password
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: username
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: host
            - name: TZ
              value: Europe/Stockholm
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /app/data
              name: mealie-data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
