apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: its-mytabs
  name: its-mytabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: its-mytabs
  template:
    metadata:
      labels:
        app: its-mytabs
    spec:
      containers:
        - image: louislam/its-mytabs:1.7.0@sha256:2e478d3170bdbec11c9c3a6ff58fd5a2ba80c119fd78fe4b0e9f4f475b6356f8
          name: its-mytabs
          ports:
            - containerPort: 47777
          volumeMounts:
            - mountPath: /app/data
              name: its-mytabs-data
      volumes:
        - name: its-mytabs-data
          persistentVolumeClaim:
            claimName: its-mytabs-data-pvc
