apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 3100
        supplementalGroups: [3100]
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:2.6.5.5623-ls162@sha256:f2b26429893d4c4cb71941b7ee50b1bdecd9d5f9f9e02d5410615e9f4f7c8d95
          ports:
            - containerPort: 9696
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "3100"
            - name: TZ
              value: Europe/Stockholm
          resources:
            requests:
              memory: 192Mi
            limits:
              memory: 384Mi
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc-v2
