apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        fsGroup: 3100
        supplementalGroups: [3100]
      containers:
        - name: prowlarr
          image: ghcr.io/linuxserver/prowlarr:2.6.5.5623-ls161@sha256:c96b56d94d116a9f4de94bc23d3381689492e6c3cfb7435320e8d982e406f99a
          ports:
            - containerPort: 9696
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "3100"
            - name: TZ
              value: Europe/Stockholm
          resources:
            requests:
              memory: 192Mi
            limits:
              memory: 384Mi
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc-v2
