apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc-v2
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
