apiVersion: v1
kind: Service
metadata:
  labels:
    app: n8n
  name: n8n
  namespace: n8n
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5678
  selector:
    app: n8n
    role: app
  type: ClusterIP
