apiVersion: v1
kind: Service
metadata:
  labels:
    app: n8n
  name: n8n
  namespace: n8n
spec:
  ports:
    - port: 80
      name: web
      protocol: TCP
      targetPort: 5678
  selector:
    app: n8n
  type: ClusterIP
