apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openvpn-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: openvpn-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: openvpn-user
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: openvpn-password
    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: openvpn-countries
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: wireguard-private-key
