apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml

configMapGenerator:
  - name: glance-configmap
    files:
      - ./config/glance.yml
