apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: christophervestman@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - selector:
          dnsZones:
            - christophervestman.com
        dns01:
          webhook:
            groupName: christophervestman.com
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-secret
                key: api-key
              secretKeySecretRef:
                name: porkbun-secret
                key: secret-key
