apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: cloudflare-api-tokens
    creationPolicy: Owner
  data:
    - secretKey: cert-manager-token
      remoteRef:
        key: cert-manager-api-token
