apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallos
  namespace: wallos
  labels:
    app: wallos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallos
  template:
    metadata:
      labels:
        app: wallos
    spec:
      containers:
        - name: wallos
          image: bellamy/wallos:5.8.1@sha256:0f049dbab45b9f8e8d43b84fd1b77ef9e55909bd1a384a0f4fe8597ab68a1d5d
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Europe/Stockholm
          volumeMounts:
            - name: wallos-storage
              mountPath: /var/www/html/db
              subPath: db
            - name: wallos-storage
              mountPath: /var/www/html/images/uploads/logos
              subPath: logos
      volumes:
        - name: wallos-storage
          persistentVolumeClaim:
            claimName: wallos-pvc
      restartPolicy: Always
