apiVersion: v1
kind: Service
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ports:
    - port: 80
  selector:
    app: audiobookshelf
  type: ClusterIP
