apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tududi-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: tududi-secrets
    creationPolicy: Owner
  data:
    - secretKey: email
      remoteRef:
        key: tududi-email
    - secretKey: password
      remoteRef:
        key: tududi-password
    - secretKey: session-secret
      remoteRef:
        key: tududi-session
