apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-app-secrets
  namespace: firefly
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  target:
    name: firefly-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: firefly-app-key
    - secretKey: STATIC_CRON_TOKEN
      remoteRef:
        key: firefly-static-cron-token
    - secretKey: FIREFLY_III_ACCESS_TOKEN
      remoteRef:
        key: firefly-importer-token
