apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-upload
  namespace: firefly
spec:
  storageClassName: truenas-pvc-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
