# Offsite Backup
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: paperless-ngx-db-backup-hexabyte
  namespace: paperless-ngx
spec:
  retentionPolicy: "7d"
  configuration:
    destinationPath: "s3://cnpg-backups/paperless-ngx/"
    endpointURL: "https://s3.hexabyte.se"
    s3Credentials:
      accessKeyId:
        name: hexabyte-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: hexabyte-credentials
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
      jobs: 2
