apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - firefly
  - immich
  - kaneo
  - lifedata
  # - linkding
  - linkwarden
  - mealie
  - n8n
  - paperless-ngx
  # - sure
