apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-pvc-nfs
  accessModes:
    - ReadWriteOnce

