apiVersion: v1
data:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:5ZDuEPKdMaimSQV1xSKZ374yOO8nyUcT/9ZISKeH/hSGU2lnrCyi9Q==,iv:M7vAJPSf9YsqnvA/xa7piLWsYFJuEJXRguzFpIYFZuY=,tag:NEGvKsRp208QpMTVhzxzYw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:5xhUMYHLDy6Vj+jL,iv:0EgEsWujKouN+HfbRpGJWAZSL0slW36aVUfZjOSJGIY=,tag:epVVuxixWmMp2D1EgHFhmA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pgadmin-secret-env
sops:
    age:
        - recipient: age14l4x2993zh3lavuyc75d669889zqjzap384um9ngv08eeh9w35nqnw3jd8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcGpJazdOOGpEOWNJcUZu
            M0dRTE5ub2pBQkRTejJJUXdWMVBod1lyYUNVCmhqZk1DZlVFUFl3YmRERFRldHdp
            cDlOVGJaRHZFZmRUMlJZbjNYY2ZwR2cKLS0tIEl1VzRaandEdkt3Y3NwNXZ5U1pW
            azdvR2pORm42YTJUNnVMV0MrUDlxcXcKn2aJurnb7nytxVKhRNhxri5NqsDzTgjN
            899wKL4p5kGhEZOd+2UUdqIAND1JhnOj7gKjr9vReyppCC8Bqpv6Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-09T20:48:50Z"
    mac: ENC[AES256_GCM,data:Zk3qLYVuqajub6fSA6bv28w7r0b9BfchhDchvtlrr84gqKv2iS5Zg+OiQS6MSC5IL+XjCR9Iq5SjDIP9M95TRqugKFe4Ydj9RRnrMBuzHYoZJhrgqD50Rd8uHAmLz9pED5/ELINPXNUN9wAtHJN5B+hjF6XoJf6xUnDm0tBsMno=,iv:IHx14YRof0y5EtBmIdlXBfDSAD16Eh8gxvfTvw/VRhI=,tag:Fm84kmeU103FJiQN5cNpqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
