apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-authentik-creds
  namespace: actualbudget
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: actual-authentik-creds
    creationPolicy: Owner
  data:
    - secretKey: ACTUAL_AUTHENTIK_CLIENT_ID
      remoteRef:
        key: actual-authentik-client-id
    - secretKey: ACTUAL_AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: actual-authentik-client-secret
