apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: convertx-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: convertx-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: convertx-jwt
