theme:
  background-color: 240 21 15
  contrast-multiplier: 1.4
  negative-color: 347 70 65
  positive-color: 115 54 76
  primary-color: 217 92 83

branding:
  custom-footer: |
    <p><a href="https://github.com/druwan">github.com/druwan<a></p>

server:
  port: 8080
  proxied: true

pages:
  - name: Home
    hide-desktop-navigation: true
    width: wide
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
            timezones:
              - timezone: Europe/Stockholm
                label: Sweden
              - timezone: Asia/Colombo
                label: Sri Lanka
              - timezone: Australia/Brisbane
                label: Cairns
          - type: weather
            units: metric
            hour-format: 24h
            location: Arlanda, Sweden

      - size: full
        widgets:
          - type: server-stats
            servers:
              - type: local
                name: Satsumas
                hide-mountpoints-by-default: true
                mountpoints:
                  "/":
                    hide: false
                  "/home":
                    hide: false
          - type: monitor
            cache: 1h
            title: Apps
            sites:
              - title: Actual Budget
                url: https://actualbudget.christophervestman.com
                icon: sh:actual-budget
              # - title: Audiobookshelf
              #   url: https://audiobookshelf.christophervestman.com
              #   icon: sh:audiobookshelf
              - title: Home Assistant
                url: http://192.168.1.104:8123
                icon: sh:home-assistant
              - title: Grafana
                url: https://grafana.christophervestman.com
                icon: sh:grafana
              - title: Immich
                url: https://immich.christophervestman.com
                icon: sh:immich
              - title: Jellyfin
                url: https://jellyfin.christophervestman.com
                icon: sh:jellyfin
              - title: Jellyseerr
                url: https://jellyseerr.christophervestman.com
                icon: sh:jellyseerr
              - title: Linkding
                url: https://linkding.christophervestman.com
                icon: sh:linkding
              - title: Mealie
                url: https://mealie.christophervestman.com
                icon: sh:mealie
              - title: n8n
                url: https://n8n.christophervestman.com
                icon: sh:n8n
              - title: Paperless-ngx
                url: https://paperless-ngx.christophervestman.com
                icon: sh:paperless-ngx
              - title: pgAdmin
                url: https://pgadmin.christophervestman.com
                icon: sh:postgresql
              - title: Wallos
                url: https://wallos.christophervestman.com
                icon: sh:wallos
              # - title: Vaultwarden
              #   url: https://vaultwarden.christophervestman.com
              #   icon: sh:vaultwarden
