apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-db-v2
  namespace: linkwarden
spec:
  description: "Postgres cluster for Linkwarden"
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
  imagePullPolicy: Always
  inheritedMetadata:
    labels:
      app: linkwarden-db
      policy-type: database
  instances: 1
  storage:
    size: 2Gi
    storageClass: longhorn
    resizeInUseVolumes: true

  walStorage:
    size: 2Gi
    storageClass: longhorn

  superuserSecret:
    name: linkwarden-db-superuser

  # FRESH INSTALL: contains no backup. Have to use initdb
  # bootstrap:
  #   initdb:
  #     database: linkwarden
  #     owner: linkwarden
  #     secret:
  #       name: linkwarden-db-credentials

  # Upgrade Major version
  bootstrap:
    initdb:
      import:
        type: monolith
        databases:
          - linkwarden
        roles:
          - linkwarden
        source:
          externalCluster: linkwarden-db-v1

  externalClusters:
    - name: linkwarden-db-v1
      connectionParameters:
        host: linkwarden-db-v1-rw.linkwarden.svc.cluster.local
        user: postgres
        dbname: postgres
        sslmode: prefer
      password:
        name: linkwarden-db-superuser
        key: password

  # # DISASTER RECOVERY: Once a backup exists, replace the initdb with the block below
  # bootstrap:
  #   recovery:
  #     source: linkwarden-db-hexabyte
  #     database: linkwarden
  #     owner: linkwarden
  #     secret:
  #       name: linkwarden-db-credentials
  # externalClusters:
  #   - name: linkwarden-db-hexabyte
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: linkwarden-db-backup-hexabyte
  #         serverName: linkwarden-db

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: linkwarden-db-backup-hexabyte

  managed:
    services:
      disabledDefaultServices: ["r", "ro"]
