apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db-v0
  namespace: authentik
spec:
  description: "Postgres cluster for authentik application"
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
  imagePullPolicy: Always
  inheritedMetadata:
    labels:
      app: authentik-db
      policy-type: database
  instances: 1

  storage:
    size: 5Gi
    storageClass: truenas-nvme-nfs
    resizeInUseVolumes: true

  walStorage:
    size: 5Gi
    storageClass: truenas-nvme-nfs

  superuserSecret:
    name: authentik-db-superuser

  # FRESH INSTALL: contains no backup. Have to use initdb
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-credentials

  # DISASTER RECOVERY: Once a backup exists, replace the initdb with the block below
  # bootstrap:
  #   recovery:
  #     source: authentik-db-hexabyte
  #     database: authentik
  #     owner: authentik
  #     secret:
  #       name: authentik-db-credentials
  # externalClusters:
  #   - name: authentik-db-hexabyte
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: authentik-db-backup-hexabyte
  #         serverName: authentik-db

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-db-backup-hexabyte

  managed:
    services:
      disabledDefaultServices: ["r", "ro"]

    roles:
      - name: authentik
        ensure: present
        login: true
        createdb: false
        passwordSecret:
          name: authentik-db-credentials
