apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db-superuser
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: authentik-db-superuser
    creationPolicy: Owner
    template:
      data:
        username: "postgres"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: cnpg-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hexabyte-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: hexabyte-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: hexabyte-access-key
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: hexabyte-secret-access-key
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: restic-backup-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: authentik-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: authentik
        password: "{{ .dbPassword }}"
        AUTHENTIK_SECRET_KEY: "{{ .secretKey }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .dbPassword }}"
        AUTHENTIK_POSTGRESQL__HOST: "authentik-db-v0-rw.authentik.svc.cluster.local"
        AUTHENTIK_POSTGRESQL__PORT: "5432"
        AUTHENTIK_POSTGRESQL__NAME: "authentik"
        AUTHENTIK_POSTGRESQL__USER: "authentik"
  data:
    - secretKey: secretKey
      remoteRef:
        key: authentik-secret-key

    - secretKey: dbPassword
      remoteRef:
        key: authentik-db-password
