apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discord-bot
  name: discord-bot
  namespace: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - image: ghcr.io/druwan/discord-bot:v0.1.0
          name: discord-bot
          envFrom:
            - secretRef:
                name: discord-bot-env
