apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-credentials
  namespace: rustfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: rustfs-credentials
    creationPolicy: Owner
  data:
    - secretKey: RUSTFS_ROOT_USER
      remoteRef:
        key: rustfs-admin-user
    - secretKey: RUSTFS_ROOT_PASSWORD
      remoteRef:
        key: rustfs-admin-password
