apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data
  namespace: rustfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-pvc-nfs
  resources:
    requests:
      storage: 20Gi
