apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bento-pdf
  name: bento-pdf
  namespace: bento-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bento-pdf
  template:
    metadata:
      labels:
        app: bento-pdf
    spec:
      containers:
        - image: ghcr.io/alam00000/bentopdf-simple:2.8.8@sha256:3d62b8f8eece5fe947026ac3925ff08fda245b3d6ba2c3916b94da91e0010c74
          name: bentopdf
