apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyseerr-chart
      version: "2.7.0"
      sourceRef:
        kind: HelmRepository
        name: jellyseerr
        namespace: media
  values:
    image:
      pullPolicy: Always
      tag: "2.7.3"
    fullnameOverride: jellyseerr
    extraEnv:
      - name: TZ
        value: "Europe/Stockholm"
    config:
      persistence:
        size: 5Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: truenas-pvc-nfs
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: jellyseerr.christophervestman.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: jellyseerr-tls
          hosts:
            - jellyseerr.christophervestman.com
