apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profilarr-config-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-pvc-nfs
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profilarr-config-pvc-v2
  namespace: media
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
