apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sabnzbd
  name: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      securityContext:
        fsGroup: 3100
        supplementalGroups: [3100]
      containers:
        - name: sabnzbd
          image: ghcr.io/linuxserver/sabnzbd:5.1.0-ls267@sha256:e79d3fd9282b7fa51a3382cec9fdcc4cf736f46c9d43d188193e3ce1c7accbcd
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "3100"
            - name: TZ
              value: Europe/Stockholm
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1.5Gi"
          volumeMounts:
            - mountPath: /config
              name: sabnzbd-config
            - mountPath: /media
              name: media
      volumes:
        - name: sabnzbd-config
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
