apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyseerr-chart
      version: "2.7.0"
      sourceRef:
        kind: HelmRepository
        name: seerr
  values:
    image:
      pullPolicy: Always
      tag: "2.7.3"
    fullnameOverride: seerr
    extraEnv:
      - name: TZ
        value: "Europe/Stockholm"
    config:
      persistence:
        enabled: true
        existingClaim: seerr-config
        size: 5Gi
        accessModes:
          - ReadWriteOnce
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: seerr.christophervestman.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: seerr-tls
          hosts:
            - seerr.christophervestman.com
