apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db-v2
  namespace: immich
spec:
  description: "Postgres cluster for Immich"
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-1.1.1
  imagePullPolicy: Always
  inheritedMetadata:
    labels:
      app: immich-db
      policy-type: database
  instances: 1

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  storage:
    size: 10Gi
    storageClass: longhorn
    resizeInUseVolumes: true

  walStorage:
    size: 2Gi
    storageClass: longhorn

  superuserSecret:
    name: immich-db-superuser

  # FRESH INSTALL: contains no backup. Have to use initdb
  # bootstrap:
  #   initdb:
  #     database: immich
  #     owner: immich
  #     secret:
  #       name: immich-db-credentials
  #     postInitApplicationSQL:
  #       - CREATE EXTENSION IF NOT EXISTS vector CASCADE;
  #       - CREATE EXTENSION IF NOT EXISTS cube CASCADE;
  #       - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
  #       - CREATE EXTENSION IF NOT EXISTS pg_trgm CASCADE;

  bootstrap:
    pg_basebackup:
      source: immich-db-v1

  externalClusters:
    - name: immich-db-v1
      connectionParameters:
        host: immich-db-v1-rw.immich.svc.cluster.local
        user: streaming_replica
        dbname: immich
        sslmode: verify-ca
      sslKey:
        name: immich-db-v1-replication
        key: tls.key
      sslCert:
        name: immich-db-v1-replication
        key: tls.crt
      sslRootCert:
        name: immich-db-v1-ca
        key: ca.crt

  # # DISASTER RECOVERY: Once a backup exists, replace the initdb with the block below
  # bootstrap:
  #   recovery:
  #     source: immich-db-hexabyte
  #     database: immich
  #     owner: immich
  #     secret:
  #       name: immich-db-credentials
  # externalClusters:
  #   - name: immich-db-hexabyte
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: immich-db-backup-hexabyte
  #         serverName: immich-db

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-db-backup-hexabyte

  managed:
    services:
      disabledDefaultServices: ["r", "ro"]
    roles:
      - name: immich
        ensure: present
        login: true
        createdb: false
        passwordSecret:
          name: immich-db-credentials
