apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tududi-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-pvc-nfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tududi-uploads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-pvc-nfs
  resources:
    requests:
      storage: 1Gi
