apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - actualbudget
  # - audiobookshelf
  - authentik
  - bazarr
  - bento-pdf
  - convertx
  - discord-bot
  # - dispatcharr
  # - firefly
  - flaresolverr
  # - garage
  - glance
  - health-api
  - homeassistant
  - immich
  # - its-mytabs
  - jellyfin
  - kaneo
  # - linkding
  - linkwarden
  - mealie
  - n8n
  - outline
  - paperless-ngx
  # - pgadmin
  - profilarr
  - prowlarr
  - qbittorrent
  - radarr
  # - rustfs
  - sabnzbd
  - sonarr
  # - stirling-pdf
  # - sure
  # - tududi
  # - wallos
  # - wiki-js
