apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - actualbudget
  # - audiobookshelf
  # - bazarr
  - bento-pdf
  - convertx
  - discord-bot
  # - firefly
  # - garage
  - glance
  - immich
  - its-mytabs
  - jellyfin
  # - linkding
  - linkwarden
  - mealie
  - n8n
  - paperless-ngx
  - pgadmin
  - prowlarr
  - qbittorrent
  - radarr
  # - rustfs
  - sonarr
  # - stirling-pdf
  - tududi
  - wallos
