apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kaneo-db-v1
  namespace: kaneo
spec:
  description: "Postgres cluster for Kaneo application"
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
  imagePullPolicy: Always
  inheritedMetadata:
    labels:
      app: kaneo-db
      policy-type: database
  instances: 1

  storage:
    size: 2Gi
    storageClass: longhorn
    resizeInUseVolumes: true

  walStorage:
    size: 2Gi
    storageClass: longhorn

  superuserSecret:
    name: kaneo-db-superuser

  # # FRESH INSTALL: contains no backup. Have to use initdb
  # bootstrap:
  #   initdb:
  #     database: kaneo
  #     owner: kaneo
  #     secret:
  #       name: kaneo-db-credentials

  # Bootstrap from a previous deployment
  bootstrap:
    pg_basebackup:
      source: kaneo-db-v0

  externalClusters:
    - name: kaneo-db-v0
      connectionParameters:
        host: kaneo-db-v0-rw.kaneo.svc.cluster.local
        user: streaming_replica
        dbname: kaneo
        sslmode: verify-ca
      sslKey:
        name: kaneo-db-v0-replication
        key: tls.key
      sslCert:
        name: kaneo-db-v0-replication
        key: tls.crt
      sslRootCert:
        name: kaneo-db-v0-ca
        key: ca.crt

  # DISASTER RECOVERY: Once a backup exists, replace the initdb with the block below
  # bootstrap:
  #   recovery:
  #     source: kaneo-db-hexabyte
  #     database: kaneo
  #     owner: kaneo
  #     secret:
  #       name: kaneo-db-credentials
  # externalClusters:
  #   - name: kaneo-db-hexabyte
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: kaneo-db-backup-hexabyte
  #         serverName: kaneo-db

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: kaneo-db-backup-hexabyte

  managed:
    services:
      disabledDefaultServices: ["r", "ro"]

    roles:
      - name: kaneo
        ensure: present
        login: true
        createdb: false
        passwordSecret:
          name: kaneo-db-credentials
