apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: cloudflare-tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: tunnelToken
      remoteRef:
        key: cloudflare-tunnel-token
