apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: actualbudget
    role: app
  name: actualbudget
  namespace: actualbudget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actualbudget
  template:
    metadata:
      labels:
        app: actualbudget
        role: app
    spec:
      containers:
        - image: ghcr.io/actualbudget/actual:26.9.0@sha256:552beab3dec8c93d46b8b9245612d63c3f123b8a45063a474f53e229b17621d3
          name: actualbudget
          env:
            - name: ACTUAL_OPENID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: actual-authentik-creds
                  key: ACTUAL_AUTHENTIK_CLIENT_ID

            - name: ACTUAL_OPENID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: actual-authentik-creds
                  key: ACTUAL_AUTHENTIK_CLIENT_SECRET

            - name: ACTUAL_OPENID_DISCOVERY_URL
              value: "https://authentik.christophervestman.com/application/o/actual-budget/"
            - name: ACTUAL_OPENID_SERVER_HOSTNAME
              value: "https://actualbudget.christophervestman.com/"
          ports:
            - containerPort: 5006
          volumeMounts:
            - mountPath: /data
              name: actualbudget-data
      volumes:
        - name: actualbudget-data
          persistentVolumeClaim:
            claimName: actualbudget-data-pvc
