apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-data-pvc
  namespace: actualbudget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-d880c116-8e6c-4af2-b703-c19cdfe52269
  resources:
    requests:
      storage: 1Gi
