apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data-pvc
  namespace: linkwarden
spec:
  storageClassName: truenas-pvc-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meili-data-pvc
  namespace: linkwarden
spec:
  storageClassName: truenas-pvc-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
