apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data-pvc-v2
  namespace: linkwarden
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meili-data-pvc-v2
  namespace: linkwarden
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
