apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        fsGroup: 3100
        fsGroupChangePolicy: OnRootMismatch
        runAsUser: 33
        runAsGroup: 33
        supplementalGroups: [3100, 989]
      containers:
        - image: ghcr.io/jellyfin/jellyfin:10.11.11
          name: jellyfin
          ports:
            - containerPort: 8096
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /config
              name: jellyfin-config
            - mountPath: /cache
              name: jellyfin-cache
            - mountPath: /media
              name: media
            - mountPath: /dev/dri/renderD128
              name: render-device
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: jellyfin-cache
          persistentVolumeClaim:
            claimName: jellyfin-cache-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: render-device
          hostPath:
            path: /dev/dri/renderD128
