apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - image: dpage/pgadmin4:9.6
          name: pgadmin
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: pgadmin-secret-env
