apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data-pvc
  namespace: pgadmin
  labels:
    app: pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
