apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: twenty-db
  namespace: twenty
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: twenty-db-v1
  podMetricsEndpoints:
    - port: metrics
