apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twenty-data-pvc
  namespace: twenty
spec:
  storageClassName: truenas-nvme-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twenty-data-pvc-v1
  namespace: twenty
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
