apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkding
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runsAsGroup: 33
      containers:
        - image: sissbruecker/linkding:1.41.0
          name: linkding
          ports:
            - containerPort: 9090
          envFrom:
            - secretRef:
                name: linkding-container-env
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /etc/linkding/data
              name: linkding-data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
