apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
  namespace: linkding
spec:
  storageClassName: truenas-pvc-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
