apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: immich-buffering
  namespace: immich
spec:
  buffering:
    maxRequestBodyBytes: 0
    memRequestBodyBytes: 0 # 512MB in RAM
    requestBodyInMemorySize: 0
