apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc-v2
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: truenas-nvme-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning-model-cache-pvc-v2
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-nvme-nfs
