apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: renovate-bot-secret
    creationPolicy: Owner
    template:
      data:
        LOG_LEVEL: "debug"
        RENOVATE_TOKEN: "{{ .RENOVATE_TOKEN }}"
        RENOVATE_GITHUB_COM_TOKEN: "{{ .RENOVATE_TOKEN }}"
        RENOVATE_HOST_RULES: '[{"matchHost":"ghcr.io","hostType":"docker","token":"{{ .RENOVATE_TOKEN }}","concurrentRequestLimit":2,"maxRequestsPerSecond":2}]'
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate-token
